# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: release
sudo: required
cache: packages
bioc_packages: ggtree
r_binary_packages:
 - plyr
 - tidyr
 - stringr
os:
  - osx

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo

before_install:
  - if [[ "$OSTYPE" != "linux-gnu" ]]; then sudo tlmgr install framed titling; fi

