# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: - devel
sudo: false
cache: packages
bioc_packages: - ggtree
r_binary_packages:
 - ggplot2
 - utils
 - plyr
 - stats
 - methods
 - tidyr
 - stringr
os:
  - linux
  - osx

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo


